### ISSUE TITLE
Your website is down

### ISSUE THREAD

**Issue by mjcampagna** [recurser/exif-orientation-examples#11]
Hi,

I've been attempting to access your 2012 article, "EXIF Orientation Handling is a Ghetto", but it looks like your site is messed up. All of your URLs lead to pages of gibberish. I managed to find a Google Cache of your main page, but it also seems your articles are not cached. 

A) I thought you should know, just in case you were unaware.
B) I'd still really like to get at that article, if possible.

Thanks!

Matt

**Comment by recurser** [comment]
@mjcampagna sorry about that! I did have an issue with gzipped responses acting a bit crazy - should be all good now 👍
