### ISSUE TITLE
Sample images all have 1 orientation flag

### ISSUE THREAD

**Issue by stringcode86** [recurser/exif-orientation-examples#3]
Thank you for your blog post, it finally put me on the right track.
Im afraid there was some mistake with sample images. They all seem to have orientation flag set 0
![screenshot](https://cloud.githubusercontent.com/assets/4541819/3089043/bf89895c-e579-11e3-8c42-00b7cdc8753c.png)

**Comment by recurser** [comment]
Thanks @stringcode86 - closing this.
