### ISSUE TITLE
Most images are missing EXIF data

### ISSUE THREAD

**Issue by nlfiedler** [recurser/exif-orientation-examples#7]
Am I confused or are most of these images missing the EXIF data? Landscape_1.jpg is fine, but all of the other Landscape images have no EXIF data at all. Same with the portrait images.

**Comment by drewm** [comment]
I think you might be confused. They're working well for me here.

**Comment by nlfiedler** [comment]
Yep, I cannot confirm the conclusion I came to a month ago, nor can I remember what I must have done wrong. Just as a side note, Preview on macOS does not show EXIF data for these files. I'm guessing that's a bug on their part, because the EXIF data is there, along with JFIF, which Preview also mysteriously ignores in this case. I've seen it work plenty of other times, so I have no explanation.
